# Generated by Django 4.2.1 on 2023-05-15 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='name',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='email',
        ),
    ]
