# Generated by Django 4.2.1 on 2023-05-16 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0002_rename_name_registration_username_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='newForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=50)),
                ('mob', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('department', models.CharField(max_length=50)),
                ('courses', models.CharField(max_length=50)),
                ('puposes', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'newForm',
                'verbose_name_plural': 'newForm',
            },
        ),
        migrations.RenameField(
            model_name='login',
            old_name='name',
            new_name='username',
        ),
    ]
