# Generated by Django 4.2.1 on 2023-05-16 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0003_newform_rename_name_login_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='newform',
            name='address',
            field=models.TextField(default='abc'),
            preserve_default=False,
        ),
    ]
