# Generated by Django 4.2.1 on 2023-05-16 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0005_formpage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newform',
            old_name='puposes',
            new_name='purposes',
        ),
    ]
