# Generated by Django 4.2.1 on 2023-05-16 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0006_rename_puposes_newform_purposes'),
    ]

    operations = [
        migrations.AddField(
            model_name='newform',
            name='materials',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
