# Generated by Django 4.2.1 on 2023-05-16 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0007_newform_materials'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('age', models.IntegerField()),
                ('gender', models.CharField(blank=True, max_length=50, null=True)),
                ('mob', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('department', models.CharField(blank=True, max_length=50, null=True)),
                ('courses', models.CharField(blank=True, max_length=50, null=True)),
                ('purposes', models.CharField(blank=True, max_length=50, null=True)),
                ('materials', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'formPage',
                'verbose_name_plural': 'formPage',
            },
        ),
        migrations.DeleteModel(
            name='formPage',
        ),
        migrations.DeleteModel(
            name='newForm',
        ),
    ]
